## 3주차 수학 기초,백터,행렬, Numpy
- numpy
- ndarray
- Handling shape
- Indexing
- Slicing
- Creation function
- Operation functions
- array operations
- Comparisons
- Boolean Index
- Fancy Index
- numpy data i/o

In [1]:
import numpy as np

In [2]:
test_array = np.array(["1","4", 5, 8], float) # 하나의 타입만 허용
print(test_array)
type(test_array[3])


[1. 4. 5. 8.]


numpy.float64

In [4]:
test_array.shape

(4,)

In [6]:
test_array = np.array([[1, 2, 3,],[4, 5, 6]])

In [7]:
test_array.shape

(2, 3)

In [11]:
test_resahpe = np.array([[1, 2, 3, 4],[3, 4, 5, 6]]) # 2차원

In [12]:
test_resahpe.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 6]]])

In [14]:
test_resahpe = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
resh = test_resahpe.reshape(-1, 2)
resh

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

flatten

In [19]:
flatt = resh.flatten()
flatt

array([1, 2, 3, 4, 5, 6, 7, 8])

slicing

In [23]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
type(a[1,1])

numpy.int32

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
a[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [32]:
a[1,1:3]

array([7, 8])

In [30]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [33]:
# arange

np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
a = np.arange(0,5,0.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [42]:
a = np.arange(30)
a.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [48]:
# zeros

In [49]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [50]:
np.zeros((2, 5),np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [51]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [54]:
# identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.identity(3, np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [60]:
# eye

np.eye(3, 5, k=2) #  k->start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
test_array.sum(axis=1)

array([10, 26, 42])

In [65]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

concatenate

In [69]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])

In [73]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [77]:
# transpose
test_array = np.arange(1, 7).reshape(2, 3)
test_array

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
test_array = np.ones((2, 3), np.int32)
test_array.transpose() # 행 열 변환

array([[1, 1],
       [1, 1],
       [1, 1]])

In [85]:
test_array * 3

array([[3, 3, 3],
       [3, 3, 3]])

In [86]:
# all & any - 일종의 브로드캐스팅

a = np.arange(10)

In [87]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [90]:
np.any(a>5) # any - 하나라도 만족하면 True

True

In [94]:
np.any(a < 0)

False

In [95]:
# all 모두 만족
np.all(a>5)

False

In [96]:
np.all(a<10)

True

np.where
- 조건에 맞는 인덱스 값 반환
- 조건에 맞춰 반환값을 달리할 수 있음

In [100]:
a = np.array([1, 3, 0], np.float64)
a

array([1., 3., 0.])

In [104]:
np.where(a > 0, 3, 2) # 참이면 3, 거짓이면 2

array([3, 3, 2])

In [107]:
np.where(a>0) # 조건에 맞는 index값을 반환

(array([0, 1], dtype=int64),)

In [111]:
a = np.arange(0,20).reshape(-1,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [112]:
np.where()

(array([1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [121]:
a = np.array([1, 2, 4, 10, 69, 24, 0, 13]).reshape(-1,2)
a

array([[ 1,  2],
       [ 4, 10],
       [69, 24],
       [ 0, 13]])

In [122]:
np.argmax(a)

4

In [123]:
np.argmin(a)

6

- axis=1 가로, axis=0 세로

In [124]:
np.argmin(a, axis=0)

array([3, 0], dtype=int64)

In [126]:
b = np.identity(5)

In [127]:
b > 0

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [133]:
b = np.arange(0,20).reshape(4, 5)

In [155]:
r = np.random.rand(4, 5) * 100
r = r.astype(np.int32)
r

array([[53, 56, 88,  3, 89],
       [26, 52, 49, 18, 94],
       [ 3, 22, 30, 85, 88],
       [ 9, 51, 63, 37, 10]])

In [166]:
b = r > 30
b.astype(np.int32)

array([[1, 1, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0]])

In [168]:
# fancy index
a = np.array([2, 4, 6, 8])
b = np.array([0, 0, 1, 3, 2, 1], int)

In [169]:
a[b]

array([2, 2, 4, 8, 6, 4])

In [171]:
a.take(b) # take를 추천, 어떤 코드인지 알아보기 쉽다

array([2, 2, 4, 8, 6, 4])