## 3주차 수학 기초,백터,행렬, Numpy
- numpy
- ndarray
- Handling shape
- Indexing
- Slicing
- Creation function
- Operation functions
- array operations
- Comparisons
- Boolean Index
- Fancy Index
- numpy data i/o

In [1]:
import numpy as np

In [2]:
test_array = np.array(["1","4", 5, 8], float) # 하나의 타입만 허용
print(test_array)
type(test_array[3])


[1. 4. 5. 8.]


numpy.float64

In [3]:
test_array.shape

(4,)

In [4]:
test_array = np.array([[1, 2, 3,],[4, 5, 6]])

In [5]:
test_array.shape

(2, 3)

In [6]:
test_resahpe = np.array([[1, 2, 3, 4],[3, 4, 5, 6]]) # 2차원

In [7]:
test_resahpe.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 6]]])

In [8]:
test_resahpe = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
resh = test_resahpe.reshape(-1, 2)
resh

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

flatten

In [10]:
flatt = resh.flatten()
flatt

array([1, 2, 3, 4, 5, 6, 7, 8])

slicing

In [11]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
type(a[1,1])

numpy.int64

In [12]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
a[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [14]:
a[1,1:3]

array([7, 8])

In [15]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [16]:
# arange

np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
a = np.arange(0,5,0.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
a = np.arange(30)
a.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
# zeros

In [20]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [21]:
np.zeros((2, 5),np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [22]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [23]:
# identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.identity(3, np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [25]:
# eye

np.eye(3, 5, k=2) #  k->start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
test_array.sum(axis=1)

array([10, 26, 42])

In [28]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

### concatenate
- 병합
- axis 0 : 세로
- axis 1 : 가로

In [29]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])

In [30]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [31]:
# transpose
test_array = np.arange(1, 7).reshape(2, 3)
test_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
test_array = np.ones((2, 3), np.int32)
test_array.transpose() # 행 열 변환

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [33]:
test_array * 3

array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [34]:
# all & any - 일종의 브로드캐스팅

a = np.arange(10)

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [37]:
np.any(a>5) # any - 하나라도 만족하면 True

True

In [38]:
np.any(a < 0)

False

In [39]:
# all 모두 만족
np.all(a>5)

False

In [40]:
np.all(a<10)

True

np.where
- 조건에 맞는 인덱스 값 반환
- 조건에 맞춰 반환값을 달리할 수 있음

In [41]:
a = np.array([1, 3, 0], np.float64)
a

array([1., 3., 0.])

In [42]:
np.where(a > 0, 3, 2) # 참이면 3, 거짓이면 2

array([3, 3, 2])

In [43]:
np.where(a>0) # 조건에 맞는 index값을 반환

(array([0, 1]),)

In [44]:
a = np.arange(0,20).reshape(-1,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
np.where(a < 10)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [ ]:
a = np.array([1, 2, 4, 10, 69, 24, 0, 13]).reshape(-1,2)
a

In [ ]:
np.argmax(a)

In [ ]:
np.argmin(a)

- axis=1 가로, axis=0 세로

In [ ]:
np.argmin(a, axis=0)

In [ ]:
b = np.identity(5)

In [ ]:
b > 0

In [ ]:
b = np.arange(0,20).reshape(4, 5)

In [ ]:
r = np.random.rand(4, 5) * 100
r = r.astype(np.int32)
r

In [ ]:
b = r > 30
b.astype(np.int32)

In [ ]:
# fancy index
a = np.array([2, 4, 6, 8])
b = np.array([0, 0, 1, 3, 2, 1], int)

In [ ]:
a[b]

In [ ]:
a.take(b) # take를 추천, 어떤 코드인지 알아보기 쉽다

----

### 노름, 경사하강법 - 미분

In [47]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

In [62]:
def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

In [49]:
x = [-1, 2, -3,]

In [50]:
l1_norm(x)

6

In [52]:
x2 = np.array([-6, -8])

In [56]:
np.linalg.norm(x2)

10.0

In [53]:
l2_norm(x2)

10.0

In [55]:
# 두 점 사이 거리

x = np.array([-3, 0])
y = np.array([0, 4])
np.linalg.norm(x-y)

5.0

In [65]:
x = np.array([0,1])
y = np.array([0,2])


In [66]:
np.inner(x, y)

2

In [69]:
def angle(x, y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

In [70]:
angle(x, y)

0.0

In [71]:
np.inner(x,y)

2

In [72]:
x = np.array([1, -1, 1, -1])
y = np.array([4, -4, 4, -4])

In [73]:
np.inner(x,y)

16

#### Q1
- 무작위의 데이터를 가진 5X3 행렬을 가지는 numpy array와 3X2 행렬을 가지는 numpy array를 만든 후 행열곱 연산 진행

In [74]:
import numpy as np

In [115]:
arr1 = np.random.rand(5,3)

In [117]:
arr2 = np.random.rand(3,2)

In [119]:
dot = arr1.dot(arr2)

In [120]:
dot

array([[0.49488402, 0.44708482],
       [0.74202641, 0.68972403],
       [0.47123213, 0.40031902],
       [0.82614275, 0.97682023],
       [1.15176115, 1.08428661]])

In [121]:
dot = arr1 @ arr2

In [123]:
dot, dot.shape

(array([[0.49488402, 0.44708482],
        [0.74202641, 0.68972403],
        [0.47123213, 0.40031902],
        [0.82614275, 0.97682023],
        [1.15176115, 1.08428661]]),
 (5, 2))

#### Q2.concatenate
- 2개의 numpy array가 있을때, 두 numpy array의 concatenate 연산
- axis는 0,1 두개로 연산한 결과를 출력
- 각 데이터 어떤 형태로 더해지는지 확인

In [3]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

In [7]:
arr1, arr2

(array([[ 5.,  7.],
        [ 9., 11.]]),
 array([[2., 4.],
        [6., 8.]]))

In [5]:
concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

In [6]:
concat_1, concat_2

(array([[ 5.,  7.],
        [ 9., 11.],
        [ 2.,  4.],
        [ 6.,  8.]]),
 array([[ 5.,  7.,  2.,  4.],
        [ 9., 11.,  6.,  8.]]))

----

### 경사하강법 데이터 분리

3~5문제는 numpy를 이용해 정답값을 예측해보는 linear regression을 구현해보는 미션.
첫번째 단계로 데이터를 준비하는 문제

#### q3 경사하강법을 위한 데이터를 분리
- 주어진 xy 데이터를 이용해서 학습과 정답 데이터를 준비
- 문제에서 주어진 xy에서 대괄호를 한번 더 묶어줘야 문제 해결이 가능하다.

In [65]:
xy = np.array([[1, 2, 3, 4, 5, 6],
              [10, 20, 30, 40, 50, 60]], dtype=float)

In [45]:
x_train = np.split(xy, 2)[0][0]

In [46]:
y_train = np.split(xy, 2)[1][0]

In [40]:
x_train, y_train

(array([1., 2., 3., 4., 5., 6.]), array([10., 20., 30., 40., 50., 60.]))

In [47]:
x = xy[0]

In [48]:
x

array([1., 2., 3., 4., 5., 6.])

#### q4 경사하강법 구현을 위해 weight, bias 값을 정의하라

- numpy 내의 random함수를 이용

In [77]:
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

In [78]:
beta_gd, bias

(array([0.54387254]), array([0.50080374]))

#### q5 linear regression 경사하강법으로 학습하는 코드 구현
- 경사하강법 구현을 위한 학습 Loop 구현
- 최종적으로 1000회 반복했을 시 결과 출력
- 단, error의 차이의 제곱을 이용해 계산
- gd : grdient의 값는 우리가 예측하는 각 변수에 대한 미분 값

In [79]:
learning_rate = 0.001

In [86]:
for i in range(5000): # 5000회
    pred = (x_train * beta_gd) + bias
    error = ((pred - y_train) ** 2).mean()
    
    gd_w = ((pred - y_train) * 2 * x_train).mean()
    gd_b = ((pred - y_train) * 2).mean()
    
    beta_gd -= learning_rate * gd_w
    bias -= learning_rate * gd_b
    
    if i % 500 == 0:
        print(f'Epoch ({i:10d}/5000) cost: {error:10f}, w : {beta_gd.item():10f}, b:{bias.item():10f}')

Epoch (         0/5000) cost:   0.000857, w :   9.984414, b:  0.066725
Epoch (       500/5000) cost:   0.000595, w :   9.987014, b:  0.055594
Epoch (      1000/5000) cost:   0.000413, w :   9.989181, b:  0.046320
Epoch (      1500/5000) cost:   0.000287, w :   9.990985, b:  0.038593
Epoch (      2000/5000) cost:   0.000199, w :   9.992489, b:  0.032155
Epoch (      2500/5000) cost:   0.000138, w :   9.993742, b:  0.026791
Epoch (      3000/5000) cost:   0.000096, w :   9.994786, b:  0.022322
Epoch (      3500/5000) cost:   0.000067, w :   9.995656, b:  0.018598
Epoch (      4000/5000) cost:   0.000046, w :   9.996381, b:  0.015495
Epoch (      4500/5000) cost:   0.000032, w :   9.996984, b:  0.012910
